<?php
function get_provinces(){
        return array(
                array('tag'=>'TO', 'name'=>'Torino'),
                array('tag'=>'VC', 'name'=>'Vercelli'),
                array('tag'=>'NO', 'name'=>'Novara'),
                array('tag'=>'CN', 'name'=>'Cuneo'),
                array('tag'=>'AT', 'name'=>'Asti'),
                array('tag'=>'AL', 'name'=>'Alessandria'),
                array('tag'=>'BI', 'name'=>'Biella'),
                array('tag'=>'VB', 'name'=>'Verbano-Cusio-Ossola'),
                array('tag'=>'AO', 'name'=>'Valle d\'Aosta/Vallée d\'Aoste'),
                array('tag'=>'VA', 'name'=>'Varese'),
                array('tag'=>'CO', 'name'=>'Como'),
                array('tag'=>'SO', 'name'=>'Sondrio'),
                array('tag'=>'MI', 'name'=>'Milano'),
                array('tag'=>'BG', 'name'=>'Bergamo'),
                array('tag'=>'BS', 'name'=>'Brescia'),
                array('tag'=>'PV', 'name'=>'Pavia'),
                array('tag'=>'CR', 'name'=>'Cremona'),
                array('tag'=>'MN', 'name'=>'Mantova'),
                array('tag'=>'LC', 'name'=>'Lecco'),
                array('tag'=>'LO', 'name'=>'Lodi'),
                array('tag'=>'MB', 'name'=>'Monza e della Brianza'),
                array('tag'=>'BZ', 'name'=>'Bolzano/Bozen'),
                array('tag'=>'TN', 'name'=>'Trento'),
                array('tag'=>'VR', 'name'=>'Verona'),
                array('tag'=>'VI', 'name'=>'Vicenza'),
                array('tag'=>'BL', 'name'=>'Belluno'),
                array('tag'=>'TV', 'name'=>'Treviso'),
                array('tag'=>'VE', 'name'=>'Venezia'),
                array('tag'=>'PD', 'name'=>'Padova'),
                array('tag'=>'RO', 'name'=>'Rovigo'),
                array('tag'=>'UD', 'name'=>'Udine'),
                array('tag'=>'GO', 'name'=>'Gorizia'),
                array('tag'=>'TS', 'name'=>'Trieste'),
                array('tag'=>'PN', 'name'=>'Pordenone'),
                array('tag'=>'IM', 'name'=>'Imperia'),
                array('tag'=>'SV', 'name'=>'Savona'),
                array('tag'=>'GE', 'name'=>'Genova'),
                array('tag'=>'SP', 'name'=>'La Spezia'),
                array('tag'=>'PC', 'name'=>'Piacenza'),
                array('tag'=>'PR', 'name'=>'Parma'),
                array('tag'=>'RE', 'name'=>'Reggio nell\'Emilia'),
                array('tag'=>'MO', 'name'=>'Modena'),
                array('tag'=>'BO', 'name'=>'Bologna'),
                array('tag'=>'FE', 'name'=>'Ferrara'),
                array('tag'=>'RA', 'name'=>'Ravenna'),
                array('tag'=>'FC', 'name'=>'Forlì-Cesena'),
                array('tag'=>'RN', 'name'=>'Rimini'),
                array('tag'=>'MS', 'name'=>'Massa-Carrara'),
                array('tag'=>'LU', 'name'=>'Lucca'),
                array('tag'=>'PT', 'name'=>'Pistoia'),
                array('tag'=>'FI', 'name'=>'Firenze'),
                array('tag'=>'LI', 'name'=>'Livorno'),
                array('tag'=>'PI', 'name'=>'Pisa'),
                array('tag'=>'AR', 'name'=>'Arezzo'),
                array('tag'=>'SI', 'name'=>'Siena'),
                array('tag'=>'GR', 'name'=>'Grosseto'),
                array('tag'=>'PO', 'name'=>'Prato'),
                array('tag'=>'PG', 'name'=>'Perugia'),
                array('tag'=>'TR', 'name'=>'Terni'),
                array('tag'=>'PU', 'name'=>'Pesaro e Urbino'),
                array('tag'=>'AN', 'name'=>'Ancona'),
                array('tag'=>'MC', 'name'=>'Macerata'),
                array('tag'=>'AP', 'name'=>'Ascoli Piceno'),
                array('tag'=>'FM', 'name'=>'Fermo'),
                array('tag'=>'VT', 'name'=>'Viterbo'),
                array('tag'=>'RI', 'name'=>'Rieti'),
                array('tag'=>'RM', 'name'=>'Roma'),
                array('tag'=>'LT', 'name'=>'Latina'),
                array('tag'=>'FR', 'name'=>'Frosinone'),
                array('tag'=>'AQ', 'name'=>'L\'Aquila'),
                array('tag'=>'TE', 'name'=>'Teramo'),
                array('tag'=>'PE', 'name'=>'Pescara'),
                array('tag'=>'CH', 'name'=>'Chieti'),
                array('tag'=>'CB', 'name'=>'Campobasso'),
                array('tag'=>'IS', 'name'=>'Isernia'),
                array('tag'=>'CE', 'name'=>'Caserta'),
                array('tag'=>'BN', 'name'=>'Benevento'),
                array('tag'=>'NA', 'name'=>'Napoli'),
                array('tag'=>'AV', 'name'=>'Avellino'),
                array('tag'=>'SA', 'name'=>'Salerno'),
                array('tag'=>'FG', 'name'=>'Foggia'),
                array('tag'=>'BA', 'name'=>'Bari'),
                array('tag'=>'TA', 'name'=>'Taranto'),
                array('tag'=>'BR', 'name'=>'Brindisi'),
                array('tag'=>'LE', 'name'=>'Lecce'),
                array('tag'=>'BT', 'name'=>'Barletta-Andria-Trani'),
                array('tag'=>'PZ', 'name'=>'Potenza'),
                array('tag'=>'MT', 'name'=>'Matera'),
                array('tag'=>'CS', 'name'=>'Cosenza'),
                array('tag'=>'CZ', 'name'=>'Catanzaro'),
                array('tag'=>'RC', 'name'=>'Reggio di Calabria'),
                array('tag'=>'KR', 'name'=>'Crotone'),
                array('tag'=>'VV', 'name'=>'Vibo Valentia'),
                array('tag'=>'TP', 'name'=>'Trapani'),
                array('tag'=>'PA', 'name'=>'Palermo'),
                array('tag'=>'ME', 'name'=>'Messina'),
                array('tag'=>'AG', 'name'=>'Agrigento'),
                array('tag'=>'CL', 'name'=>'Caltanissetta'),
                array('tag'=>'EN', 'name'=>'Enna'),
                array('tag'=>'CT', 'name'=>'Catania'),
                array('tag'=>'RG', 'name'=>'Ragusa'),
                array('tag'=>'SR', 'name'=>'Siracusa'),
                array('tag'=>'SS', 'name'=>'Sassari'),
                array('tag'=>'NU', 'name'=>'Nuoro'),
                array('tag'=>'CA', 'name'=>'Cagliari'),
                array('tag'=>'OR', 'name'=>'Oristano'),
                array('tag'=>'OT', 'name'=>'Olbia-Tempio'),
                array('tag'=>'OG', 'name'=>'Ogliastra'),
                array('tag'=>'VS', 'name'=>'Medio Campidano'),
                array('tag'=>'CI', 'name'=>'Carbonia-Iglesias'),

        );
}
